eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.2:8761/eureka
spring:
  data:
    mongodb:
      host: 35.195.104.42
      port: 27017
      database: admin
      username: toto
      password: toto
  rabbitmq:
    host: 192.168.1.52
    username: guest
    password: guest
address:
  user-profile: localhost